name: Update git config
runs:
  using: "composite"
  steps:
    - name: Update git config
      shell: bash
      run: |
        git config --global user.name "William Blake"
        git config --global user.email "iosteam@anytype.io"