name: License Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  license-checks:
    name: License Checks
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Xcode Cache
        uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-
          swiftpm-cache-key: spm-soucepackages-${{ github.workflow }}-${{ hashFiles('Anytype.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          swiftpm-cache-restore-keys: spm-soucepackages-${{ github.workflow }}-
          sourcepackages-directory: ./build/SourcePackages
      
      - name: Prepare deps
        uses: ./.github/actions/prepare-deps

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.1'

      - name: Download Middleware
        run: make setup-middle-ci
        env:
          MIDDLEWARE_TOKEN: ${{ secrets.MIDDLEWARE_TOKEN }}

      - name: License Checks
        uses: ./.github/actions/license-checks
