name: Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:

permissions:
  # Delete cache
  actions: write

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Xcode Cache
        uses: irgaly/xcode-cache@v1
        with:
          key: xcode-cache-deriveddata-${{ github.sha }}
          restore-keys: xcode-cache-deriveddata-
          swiftpm-cache-key: spm-soucepackages-${{ github.sha }}
          swiftpm-cache-restore-keys: spm-soucepackages-
          # Delete old cache and override from this build
          # If will works fine, add new workflow for update cache after merge in develop and use this workflow in read-only mode
          delete-used-deriveddata-cache: true
      
      - name: Prepare deps
        uses: ./.github/actions/prepare-deps

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.1'

      - name: Download Middleware
        run: make setup-middle-ci
        env:
          MIDDLEWARE_TOKEN: ${{ secrets.MIDDLEWARE_TOKEN }}

      - name: Run unit tests
        run: bundle exec fastlane tests skip_notify:true
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 900
          FASTLANE_XCODE_LIST_TIMEOUT: 900
