name: Anytype

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: 'release'

jobs:
  main:
    runs-on: ${{ vars.RUNNER }}
    timeout-minutes: 50

    steps:
      - name: Install SSH key for access to repository
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_ACCESS_KEY }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
           ref: ${{ github.event.inputs.branch }}

      - name: Update git config
        uses: ./.github/actions/update-git-config

      - name: Prepare deps
        uses: ./.github/actions/prepare-deps

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: '14.3'

      - name: Download Middleware
        run: make setup-middle

      - name: License Checks
        uses: ./.github/actions/license-checks

      - name: Run unit tests
        run: bundle exec fastlane tests
        continue-on-error: true
        env:
          SLACK_URL_BUILD_TESTS: ${{ secrets.SLACK_URL_BUILD_TESTS }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 900
          FASTLANE_XCODE_LIST_TIMEOUT: 900

      - name: Build and upload to Testflight
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane release
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY_FASTLANE_MATCH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 900
          FASTLANE_XCODE_LIST_TIMEOUT: 900
