name: Fastlane test build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: false
        default: 'develop'

jobs:
  main:
    runs-on: ${{ vars.RUNNER }}
    timeout-minutes: 35

    steps:
      - name: Install SSH key for access to repository.
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_ACCESS_KEY }}

      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Prepare deps
        uses: ./.github/actions/prepare-deps

      - name: Update git config
        run: |
          git config --global url.ssh://git@github.com/.insteadOf https://github.com/
          git config --global user.name "William Blake"
          git config --global user.email "iosteam@anytype.io"

      - uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: '14.3'

      - name: Download Middleware
        run: make setup-middle

      # - name: Test comment
      #   run: bundle exec fastlane add_linear_comment from_tag:dev/0.22.0/32 to_tag:dev/0.22.0/33 comment:"Test comment \`0.23\`"
      #   env:
      #    LINEAR_TOKEN: ${{ secrets.LINEAR_TOKEN }}

      - name: Build
        run: |
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          bundle exec fastlane test_build
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY_FASTLANE_MATCH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 900
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 4
